name: Build and Lint
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 'main', 'release/**', 'golang-standards-layout' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'

      - name: Grant access to private modules
        run: git config --global url."https://${{ secrets.GO_MODULE_TOKEN }}:x-oauth-basic@github.com/cryptotradev".insteadOf "https://github.com/cryptotradev"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50.0

        # Run build of the application
      - name: Run build
        run: make build