name: Push to GCR GitHub Action
on: release
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text
          registry: gcr.io
          project_id: eco-muse-358910
          image_name: doorbell-server-0.0.1
          image_tag: latest
          dockerfile: ./docker/Dockerfile
          context: ./docker